# Generated by Django 5.0.7 on 2024-07-24 09:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_coupon_order_discount'),
        ('products', '0003_products_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='allowed_products',
            field=models.ManyToManyField(blank=True, related_name='p_coupons', to='products.products'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, related_name='u_coupons', to=settings.AUTH_USER_MODEL),
        ),
    ]
