# Generated by Django 5.0.7 on 2024-07-22 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.category_type'),
        ),
    ]
