# Generated by Django 5.0.6 on 2024-08-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productview'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='lock_session',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='lock_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
